projects:
  app-client:
    schemaPath: ./graphql/schema.graphql
    includes: [
      "./graphql/**/*.graphql",
      "./graphql/**/*.gql"
    ]
    extensions:
      endpoints:
        default: ${env:APP_URL}:${env:APP_PORT}
