projects:
  app:
    schemaPath: schema.graphql
    includes: [
      "**/*.graphql",
      "**/*.gql"
    ]
    exclude: [
      "**/*seed*.graphql",
      "**/*seed*.gql"
    ]
    extensions:
      endpoints:
        default: ${env:APP_URL}:${env:APP_PORT}
  # app-client:
  #   schemaPath: ../../frontend/graphql/schema.graphql
  #   includes: [
  #     "**/graphql/**/*.graphql",
  #     "**/graphql/**/*.gql"
  #   ]
  #   extensions:
  #     endpoints:
  #       default: ${env:APP_URL}:${env:APP_PORT}
  prisma:
    schemaPath: ./backend/src/prisma/generated/prisma.graphql
    includes: [
      "**/*.graphql",
      "**/*.gql"
    ]
    extensions:
      prisma: prisma.yml
      generate-fragments:
        output: ./generated/prisma.fragments.graphql
        generator: graphql
