#!/bin/bash

cat ./generated/prisma.fragments.graphql >> ./generated/prisma.graphql

rm ./generated/prisma.fragments.graphql

prisma-binding -i ./generated/prisma.graphql -b ./generated/prisma-binding/index.ts -l typescript

gg
